### ISSUE TITLE
Docker run not working

### ISSUE THREAD

**Issue by thiagomg** [WillKirkmanM/music#142]
Hello!

When I tried to run with docker run it was spinning (loading) with nothing ever loading. I tried to run as interactive and I got this error:

```bash
$ sudo docker run -it -p 1993:1993   -v "/home/thiago/.config/ParsonLabsMusic:/ParsonLabsMusic"   -v "/home/thiago/Music:/music" ghcr.io/willkirkmanm/music
Failed to create database directory: Permission denied (os error 13)
Failed to create database file: No such file or directory (os error 2)
```

The mapped directories exist:

```bash
thiago@pop-os:~/opt/music$ ls -la /home/thiago/Music | wc -l
138
thiago@pop-os:~/opt/music$ ls -la /home/thiago/.config/ParsonLabsMusic
total 8
drwxr-xr-x  2 root   root   4096 Oct  6 12:11 .
drwxr-xr-x 45 thiago thiago 4096 Oct  6 12:11 ..
```

Thanks!

**Comment by WillKirkmanM** [comment]
Hello @thiagomg Thank you very much for trying Music and the very diligent attempt to provide me with all the information needed to solve this! I am terribly sorry for my carelessness in the attempt to get it working,

I have managed to reproduce the bug on my VM, the issue lies with permissions; When mounting directories from a host system onto a container through the `-v` flag, the container needs appropriate permissions to read and write to those directories. Docker, by default runs as `root` **inside the container** which leads to permission nuances when they are not accessible by the `root` in the container

A quick solution would be to ensure that the container runs with the same user and group ID's as the host by adding `--user $(id -u):$(id -g)`, the full `docker run` command would look like this:

```bash
docker run -d \
  --name parsonlabs-music \
  -p 1993:1993 \
  -v "/path/to/config:/ParsonLabsMusic" \
  -v "/path/to/music:/music" \
  --user $(id -u):$(id -g) \
  --restart unless-stopped \
  ghcr.io/willkirkmanm/music
```

or in your case:

```bash
docker run -d \
  --name parsonlabs-music \
  -p 1993:1993 \
  -v "/home/thiago/.config/ParsonLabsMusic:/ParsonLabsMusic" \
  -v "/home/thiago/Music:/music" \
  --user $(id -u):$(id -g) \
  --restart unless-stopped \
  ghcr.io/willkirkmanm/music`
```

The fix to this is ensuring the directories are created within the docker container by adding these lines in the last stage of the `Dockerfile`:

```dockerfile
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 --ingroup nodejs nextjs
RUN chown -R nextjs:nodejs /app
RUN mkdir -p /ParsonLabsMusic /music && chown -R nextjs:nodejs /ParsonLabsMusic /music
USER nextjs
```

The last stage of the `Dockerfile` would look like this

```dockerfile
FROM debian:bookworm-slim AS runner
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl3 \
    sqlite3 \
    libsqlite3-dev \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user and group
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 --ingroup nodejs nextjs

# Change ownership of the /app directory to the nextjs user
RUN chown -R nextjs:nodejs /app

# Make sure directories exist and have correct permissions
RUN mkdir -p /ParsonLabsMusic /music && chown -R nextjs:nodejs /ParsonLabsMusic /music

USER nextjs
COPY --from=backend-builder --chown=nextjs:nodejs /usr/src/crates/backend/target/release/music-server /usr/local/bin/music-server
COPY --from=backend-builder --chown=nextjs:nodejs /usr/src/crates/backend/music.db /usr/src/crates/backend/music.db
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/out ./apps/web/out

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV RUNNING_IN_DOCKER=true

EXPOSE 1993
EXPOSE 7700

CMD ["/usr/local/bin/music-server", "--port", "1993"]
```

I have committed these changes and will be pushed and therefore fixed in the next update coming tomorrow, the update will fix repeated authentication requests.

Thank You & My Reiterated Apologies
– WillKirkmanM

**Comment by thiagomg** [comment]
Thank you very much for your quick response. I will try and let you know if it fixes on my side too.
I deeply appreciate your prompt response.

Best regards and success for you and your project.

Thiago.

**Comment by thiagomg** [comment]
It worked, thanks!
